/**
 * HP2-11 scoring fixtures: the independent reference for PRD §10 (Hackathon Mock v1). Each
 * fixture has a stable ID and version, its PRD/acceptance references, inputs, the hand
 * calculation and the expected result and workflow state. Expected values are written from
 * the PRD, not generated by code; `worksheet.test.ts` recomputes them with the independent
 * worksheet and `conformance.test.ts` executes them against the implementation.
 *
 * Changing an expected value requires an approved scoring-rule change (decision register
 * O01–O03, O09): bump the fixture's `version` and record the rule change in `changes`.
 */

export const worksheetVersion = 1;

/** The profile and form the fixtures are written against (PRD §10.1, O01). */
export const inputVersions = {
  profile: { id: 'hackathon-mock-v1', name: 'Hackathon Mock v1', version: 1 },
  formula: 'cpi-formula-1',
  rounding: 'half_up_2dp',
  form: { id: 'form-v1', version: 1 },
  weights: {
    procedures: 10,
    riskAssessment: 15,
    mitigationPlan: 15,
    implementation: 60,
  },
  label:
    'Hackathon Mock v1 — Proposed Demo Rubric v1 (PRD §10.1). A simulation, not official EACC scoring.',
} as const;

export type DecisionRef = 'O01' | 'O02' | 'O03' | 'O04' | 'O06' | 'O09' | 'O10';

/** Equal demo weights of 1 unless a fixture says otherwise (PRD §10.4). */
export interface MilestoneRow {
  code: string;
  weight: number;
  /** The institution's completion claim: true, false, or unanswered (null). */
  claimed: boolean | null;
  /** File IDs the claim references. */
  evidence: string[];
}

export interface DecisionRow {
  code: string;
  outcome: 'accepted' | 'rejected';
  /** The submission revision the officer assessed. */
  revision: number;
}

export interface QuarterInputs {
  kind: 'quarter';
  maxPoints: number;
  /** The locked baseline due in the quarter; empty while the baseline awaits approval. */
  milestones: MilestoneRow[];
  /** Claims about milestones from other quarters (corrective progress), not in this baseline. */
  outOfBaseline?: MilestoneRow[];
  /** Files supplied with the latest revision. */
  suppliedFiles: string[];
  decisions: DecisionRow[];
  lateness?: { submittedAt: string; deadline: string };
}

export interface FoundationVersion {
  id: string;
  status: 'active' | 'superseded' | 'withdrawn';
  effectiveFrom: string;
  effectiveTo: string | null;
  acceptedChecks: number;
}

export type FoundationInput =
  { acceptedChecks: number } | { versions: FoundationVersion[] };

export type QuarterRow =
  | { status: 'finalized'; accepted: number; locked: number }
  | {
      status: 'closed_without_submission' | 'awaiting_review' | 'not_submitted';
      locked: number;
    };

export interface AnnualInputs {
  kind: 'annual';
  cutoff: string;
  foundations: {
    procedures: FoundationInput;
    riskAssessment: FoundationInput;
    mitigationPlan: FoundationInput;
  };
  quarters: [QuarterRow, QuarterRow, QuarterRow, QuarterRow];
}

export type ExpectedScore =
  /** `fraction` is accepted weight / locked weight, unreduced, so the denominator shows. */
  | { status: 'calculated'; fraction: string; points: string }
  | {
      status: 'pending';
      reason: 'baseline_not_approved' | 'awaiting_officer_decisions';
    };

export interface QuarterExpected {
  provisional: ExpectedScore;
  reviewed: { revision: number; score: ExpectedScore }[];
  daysLate?: number;
}

export type AnnualExpected =
  | {
      status: 'calculated';
      foundationPoints: string;
      /** Reduced. */
      implementationAverage: string;
      implementationPoints: string;
      total: string;
    }
  | { status: 'pending' };

interface FixtureBase {
  id: string;
  version: number;
  title: string;
  references: { prd: string[]; at: string[]; decisions: DecisionRef[] };
  /** The hand calculation, one step per line. */
  calculation: string[];
  /** The workflow state the implementation must show alongside the number. */
  workflow: string;
  /** Integration or mock tests that execute the workflow part beyond the arithmetic. */
  workflowTests: string[];
  /** Approved rule changes that altered the expected result, newest first. */
  changes: string[];
}

export type ScoringFixture =
  | (FixtureBase & { inputs: QuarterInputs; expected: QuarterExpected })
  | (FixtureBase & { inputs: AnnualInputs; expected: AnnualExpected });

const tests = {
  apiYear:
    'apps/api/src/simulation/simulation.int.test.ts › reproduces every expected annual result and stays pending until publication (PRD §17, AT18, AT19)',
  mockYear:
    'apps/web/src/mocks/annual.test.ts › reproduces every expected annual result and stays pending until publication',
  at07: 'apps/api/src/reporting/reporting.int.test.ts › submits once per idempotency key and hides scores from the receipt (AT06, AT07)',
  at08: 'apps/api/src/review/review.int.test.ts › records decisions and finalizes the latest revision',
  at09: 'apps/api/src/review/review.int.test.ts › keeps the earlier receipt, re-reviews changed milestones and carries forward only by confirmation (AT09, AT27)',
  at11: 'apps/api/src/reporting/reporting.int.test.ts › treats the last second as on time and the next as one day late (AT11)',
  at14api:
    'apps/api/src/annual/annual.int.test.ts › blocks publication while a quarter awaits officer review (AT14)',
  at14mock:
    'apps/web/src/mocks/acceptance.test.ts › blocks publication while a quarter awaits officer review',
  at15: 'apps/api/src/annual/annual.int.test.ts › releases a result, withholds numbers before release, and corrects through a case (AT15, AT18–AT20)',
  at17: 'apps/api/src/planning/planning.int.test.ts › versions confirmed amendments for unopened periods and refuses opened ones (AT17)',
  at25: 'apps/api/src/planning/planning.int.test.ts › confirms a seeded historical baseline so the quarter can be finalized (AT25)',
  at28: 'apps/api/src/planning/planning.int.test.ts › scores claimed checks provisionally, reviewed checks after review, and drops credit on supersession (AT28)',
  at29: 'apps/api/src/review/review.int.test.ts › closes an unanswered clarification only after the window and the cutoff (AT29)',
  at31: 'apps/api/src/planning/planning.int.test.ts › requires every check and a rationale, and lets the officer return an inflated proposal (AT31)',
} as const;

const cutoff = '2027-07-31T23:59:59+03:00';
const full = { acceptedChecks: 4 };
const fullFoundations = {
  procedures: full,
  riskAssessment: full,
  mitigationPlan: full,
};
const fin = (accepted: number, locked = 4): QuarterRow => ({
  status: 'finalized',
  accepted,
  locked,
});
const ms = (
  code: string,
  claimed: boolean | null,
  evidence: string[] = [],
): MilestoneRow => ({ code, weight: 1, claimed, evidence });
const decide = (
  revision: number,
  outcomes: Record<string, 'accepted' | 'rejected'>,
): DecisionRow[] =>
  Object.entries(outcomes).map(([code, outcome]) => ({
    code,
    outcome,
    revision,
  }));
const allAccepted = (codes: string[], revision = 1) =>
  decide(revision, Object.fromEntries(codes.map((code) => [code, 'accepted'])));
const codes = (count: number, from = 1) =>
  Array.from(
    { length: count },
    (_, i) => `M-${String(from + i).padStart(2, '0')}`,
  );
const calc = (fraction: string, points: string): ExpectedScore => ({
  status: 'calculated',
  fraction,
  points,
});
const awaiting: ExpectedScore = {
  status: 'pending',
  reason: 'awaiting_officer_decisions',
};
const base = { version: 1, changes: [] as string[] };

export const scoringFixtures: ScoringFixture[] = [
  {
    ...base,
    id: 'SF-01',
    title: 'Example A: full foundations, implementation 0.50, 0.75, 1, 1',
    references: {
      prd: ['§10.5', '§10.6 Example A', '§17.1 DEMO-001'],
      at: ['AT16'],
      decisions: ['O01', 'O02', 'O03'],
    },
    inputs: {
      kind: 'annual',
      cutoff,
      foundations: fullFoundations,
      quarters: [fin(2), fin(3), fin(4), fin(4)],
    },
    calculation: [
      'Foundations: 10 × 4/4 + 15 × 4/4 + 15 × 4/4 = 40',
      'Implementation average: (0.50 + 0.75 + 1 + 1) ÷ 4 = 3.25 ÷ 4 = 0.8125 (13/16)',
      'Implementation: 60 × 0.8125 = 48.75',
      'Annual: 40 + 48.75 = 88.75',
    ],
    expected: {
      status: 'calculated',
      foundationPoints: '40.00',
      implementationAverage: '13/16',
      implementationPoints: '48.75',
      total: '88.75',
    },
    workflow:
      'Every quarter and foundation finalized; all four quarters stay separately visible; foundations counted once.',
    workflowTests: [tests.apiYear, tests.mockYear],
  },
  {
    ...base,
    id: 'SF-02',
    title: 'Example B before Q3 closure: annual result pending',
    references: {
      prd: ['§10.5', '§10.6 Example B', '§17.1 DEMO-005'],
      at: ['AT14', 'AT15'],
      decisions: ['O03', 'O10'],
    },
    inputs: {
      kind: 'annual',
      cutoff,
      foundations: {
        procedures: full,
        riskAssessment: { acceptedChecks: 3 },
        mitigationPlan: full,
      },
      quarters: [
        fin(2),
        fin(3),
        { status: 'not_submitted', locked: 4 },
        fin(4),
      ],
    },
    calculation: [
      'Q3 has no submission and no officer disposition: I3 does not exist yet.',
      'No renormalization over reported quarters and no silent zero: the annual result is pending, not 70.00.',
    ],
    expected: { status: 'pending' },
    workflow:
      'Annual result pending with the reason "Q3 not submitted and not yet closed"; publication blocked.',
    workflowTests: [tests.at15, tests.apiYear],
  },
  {
    ...base,
    id: 'SF-03',
    title: 'Example B after explicit Q3 closure',
    references: {
      prd: ['§10.5', '§10.6 Example B', '§17.1 DEMO-005'],
      at: ['AT15'],
      decisions: ['O02', 'O03', 'O10'],
    },
    inputs: {
      kind: 'annual',
      cutoff,
      foundations: {
        procedures: full,
        riskAssessment: { acceptedChecks: 3 },
        mitigationPlan: full,
      },
      quarters: [
        fin(2),
        fin(3),
        { status: 'closed_without_submission', locked: 4 },
        fin(4),
      ],
    },
    calculation: [
      'Foundations: 10 × 4/4 + 15 × 3/4 + 15 × 4/4 = 10 + 11.25 + 15 = 36.25',
      'Q3 closed for nonresponse by the officer after the cutoff, with a reason: I3 = 0',
      'Implementation average: (0.50 + 0.75 + 0 + 1) ÷ 4 = 2.25 ÷ 4 = 0.5625 (9/16)',
      'Implementation: 60 × 0.5625 = 33.75',
      'Annual: 36.25 + 33.75 = 70.00',
    ],
    expected: {
      status: 'calculated',
      foundationPoints: '36.25',
      implementationAverage: '9/16',
      implementationPoints: '33.75',
      total: '70.00',
    },
    workflow:
      'Q3 shows "closed without submission" with the officer and reason; the zero is an explicit disposition.',
    workflowTests: [tests.at15, tests.apiYear, tests.mockYear],
  },
  {
    ...base,
    id: 'SF-04',
    title:
      'Worked case Q1 (DEMO-001 story): provisional I1 = 1, reviewed I1 = 0.75',
    references: {
      prd: ['§3.3', '§10.4'],
      at: ['AT32'],
      decisions: ['O02'],
    },
    inputs: {
      kind: 'quarter',
      maxPoints: 60,
      milestones: [
        ms('M-01', true, ['ev-progress-report']),
        ms('M-02', true, ['ev-cpc-minutes']),
        ms('M-03', true, ['ev-cpc-minutes']),
        ms('M-04', true, ['ev-iao-minutes']),
      ],
      suppliedFiles: ['ev-progress-report', 'ev-cpc-minutes', 'ev-iao-minutes'],
      decisions: decide(1, {
        'M-01': 'rejected',
        'M-02': 'accepted',
        'M-03': 'accepted',
        'M-04': 'accepted',
      }),
    },
    calculation: [
      'Provisional: four claims, each referencing a supplied file: 4/4 = 1 → 60 × 1 = 60.00 (Q1 contribution 15.00)',
      'Reviewed: M-01 (exception review) unsupported and rejected with a reason; M-02–M-04 accepted: 3/4 = 0.75',
      'Reviewed points: 60 × 0.75 = 45.00 (Q1 annual contribution 60 × 0.75 ÷ 4 = 11.25)',
    ],
    expected: {
      provisional: calc('4/4', '60.00'),
      reviewed: [{ revision: 1, score: calc('3/4', '45.00') }],
    },
    workflow:
      'Decision history keeps both values and the rejected M-01 reason; no score visible to the institution before publication.',
    workflowTests: [tests.at08, tests.apiYear],
  },
  {
    ...base,
    id: 'SF-05',
    title:
      'Worked case annual: full foundations, reviewed 0.75, 1, 1, 1 (separate from Example A)',
    references: {
      prd: ['§3.3', '§10.5', '§17.1 DEMO-004'],
      at: ['AT32'],
      decisions: ['O01', 'O03'],
    },
    inputs: {
      kind: 'annual',
      cutoff,
      foundations: fullFoundations,
      quarters: [fin(3), fin(4), fin(4), fin(4)],
    },
    calculation: [
      'Foundations: 40',
      'Implementation average: (0.75 + 1 + 1 + 1) ÷ 4 = 3.75 ÷ 4 = 0.9375 (15/16)',
      'Implementation: 60 × 0.9375 = 56.25',
      'Annual: 40 + 56.25 = 96.25',
    ],
    expected: {
      status: 'calculated',
      foundationPoints: '40.00',
      implementationAverage: '15/16',
      implementationPoints: '56.25',
      total: '96.25',
    },
    workflow:
      'Published result retains the rejected Q1 claim; the institution sees only its own released result.',
    workflowTests: [tests.apiYear, tests.mockYear],
  },
  {
    ...base,
    id: 'SF-06',
    title: 'Example C: four claims supplied, three accepted',
    references: {
      prd: ['§10.6 Example C', '§17.1 DEMO-004'],
      at: ['AT08'],
      decisions: ['O02'],
    },
    inputs: {
      kind: 'quarter',
      maxPoints: 60,
      milestones: [
        ms('M-01', true, ['ev-1']),
        ms('M-02', true, ['ev-2']),
        ms('M-03', true, ['ev-3']),
        ms('M-04', true, ['ev-4']),
      ],
      suppliedFiles: ['ev-1', 'ev-2', 'ev-3', 'ev-4'],
      decisions: decide(1, {
        'M-01': 'accepted',
        'M-02': 'accepted',
        'M-03': 'accepted',
        'M-04': 'rejected',
      }),
    },
    calculation: [
      'Provisional: 4/4 claimed with supplied files → 60 × 4/4 = 60.00',
      'Reviewed: officer finds M-04 unsupported → 60 × 3/4 = 45.00',
      'The upload did not establish the fourth achievement.',
    ],
    expected: {
      provisional: calc('4/4', '60.00'),
      reviewed: [{ revision: 1, score: calc('3/4', '45.00') }],
    },
    workflow:
      'Both values retained in the decision history with the rejected criterion’s reason and evidence reference.',
    workflowTests: [tests.at08],
  },
  {
    ...base,
    id: 'SF-07',
    title: 'Example D: locked denominator, four of eight completed',
    references: {
      prd: ['§10.4', '§10.6 Example D'],
      at: ['AT17'],
      decisions: ['O09'],
    },
    inputs: {
      kind: 'quarter',
      maxPoints: 60,
      milestones: [
        ...codes(4).map((code) => ms(code, true, ['ev-1'])),
        ...codes(4, 5).map((code) => ms(code, false)),
      ],
      suppliedFiles: ['ev-1'],
      decisions: decide(1, {
        ...Object.fromEntries(codes(4).map((code) => [code, 'accepted'])),
        ...Object.fromEntries(codes(4, 5).map((code) => [code, 'rejected'])),
      }),
    },
    calculation: [
      'Locked baseline: 8 milestones of weight 1; 4 completed and accepted',
      'I = 4/8 = 0.50 → 60 × 0.50 = 30.00',
      'Deleting the four unfinished rows is refused: the result never becomes 4/4.',
    ],
    expected: {
      provisional: calc('4/8', '30.00'),
      reviewed: [{ revision: 1, score: calc('4/8', '30.00') }],
    },
    workflow:
      'Deleting or retrospectively moving unfinished milestones is refused; an amendment path is required.',
    workflowTests: [tests.at17],
  },
  {
    ...base,
    id: 'SF-08',
    title: 'Example E: submitted one day late, same accepted achievement',
    references: {
      prd: ['§10.2', '§10.6 Example E', '§17.1 DEMO-003'],
      at: ['AT11'],
      decisions: ['O04'],
    },
    inputs: {
      kind: 'quarter',
      maxPoints: 60,
      milestones: codes(4).map((code) => ms(code, true, ['ev-1'])),
      suppliedFiles: ['ev-1'],
      decisions: allAccepted(codes(4)),
      lateness: {
        submittedAt: '2026-10-16T09:00:00+03:00',
        deadline: '2026-10-15T23:59:59+03:00',
      },
    },
    calculation: [
      'Achievement: 4/4 accepted → 60 × 1 = 60.00, identical to the on-time case',
      'Lateness: deadline 15 Oct 2026 23:59:59 EAT, submitted 16 Oct 09:00 EAT → 1 calendar day late',
      'No deduction: penalty not configured in the demo.',
    ],
    expected: {
      provisional: calc('4/4', '60.00'),
      reviewed: [{ revision: 1, score: calc('4/4', '60.00') }],
      daysLate: 1,
    },
    workflow:
      'Late flag and days late shown separately ("penalty not configured"); never presented as a penalty-adjusted score.',
    workflowTests: [tests.at11, tests.apiYear],
  },
  {
    ...base,
    id: 'SF-09',
    title: 'Zero achievement',
    references: {
      prd: ['§10.3', '§10.5', '§16.1 calculation tests'],
      at: [],
      decisions: ['O02', 'O03'],
    },
    inputs: {
      kind: 'annual',
      cutoff,
      foundations: {
        procedures: { acceptedChecks: 0 },
        riskAssessment: { acceptedChecks: 0 },
        mitigationPlan: { acceptedChecks: 0 },
      },
      quarters: [fin(0), fin(0), fin(0), fin(0)],
    },
    calculation: [
      'Foundations: 10 × 0 + 15 × 0 + 15 × 0 = 0',
      'Implementation: 60 × (0 + 0 + 0 + 0) ÷ 4 = 0',
      'Annual: 0.00 — a calculated zero from final decisions, not a pending result',
    ],
    expected: {
      status: 'calculated',
      foundationPoints: '0.00',
      implementationAverage: '0/1',
      implementationPoints: '0.00',
      total: '0.00',
    },
    workflow: 'Finalized; every rejected check and milestone carries a reason.',
    workflowTests: [],
  },
  {
    ...base,
    id: 'SF-10',
    title: 'Full achievement',
    references: {
      prd: ['§10.3', '§10.5', '§16.1 calculation tests'],
      at: [],
      decisions: ['O02', 'O03'],
    },
    inputs: {
      kind: 'annual',
      cutoff,
      foundations: fullFoundations,
      quarters: [fin(4), fin(4), fin(4), fin(4)],
    },
    calculation: [
      'Foundations: 10 + 15 + 15 = 40 (counted once, never 4 × 40)',
      'Implementation: 60 × (1 + 1 + 1 + 1) ÷ 4 = 60',
      'Annual: 100.00',
    ],
    expected: {
      status: 'calculated',
      foundationPoints: '40.00',
      implementationAverage: '1/1',
      implementationPoints: '60.00',
      total: '100.00',
    },
    workflow: 'Finalized; the maximum is 100, not 160.',
    workflowTests: [tests.apiYear],
  },
  {
    ...base,
    id: 'SF-11',
    title:
      'Claimed achievement without supporting evidence: no provisional credit',
    references: {
      prd: ['§10.3', '§10.4', 'FR08'],
      at: ['AT07'],
      decisions: ['O02'],
    },
    inputs: {
      kind: 'quarter',
      maxPoints: 60,
      milestones: [
        ms('M-01', true, ['ev-1']),
        ms('M-02', true, ['ev-1']),
        ms('M-03', true, ['ev-1']),
        ms('M-04', true, []),
      ],
      suppliedFiles: ['ev-1'],
      decisions: [],
    },
    calculation: [
      'M-04 is claimed complete but references no file: provisional credit 0 for M-04',
      'Provisional: 3/4 → 60 × 0.75 = 45.00',
      'No officer decisions yet: reviewed result pending, not zero',
    ],
    expected: {
      provisional: calc('3/4', '45.00'),
      reviewed: [{ revision: 1, score: awaiting }],
    },
    workflow:
      'Receipt issued; the deficiency is explicit on the receipt and in review; reviewed score awaits officer decisions.',
    workflowTests: [tests.at07],
  },
  {
    ...base,
    id: 'SF-12',
    title: 'Supplied evidence without a completion claim: no automatic credit',
    references: {
      prd: ['§10.4', 'FR08'],
      at: [],
      decisions: ['O02'],
    },
    inputs: {
      kind: 'quarter',
      maxPoints: 60,
      milestones: [
        ms('M-01', true, ['ev-minutes']),
        ms('M-02', true, ['ev-minutes']),
        ms('M-03', false, ['ev-minutes']),
        ms('M-04', null, []),
      ],
      suppliedFiles: ['ev-minutes'],
      decisions: [],
    },
    calculation: [
      'M-03 references a supplied file but is not claimed complete; M-04 is unanswered',
      'A file cannot make an unclaimed achievement true: provisional 2/4 → 60 × 0.50 = 30.00',
    ],
    expected: {
      provisional: calc('2/4', '30.00'),
      reviewed: [{ revision: 1, score: awaiting }],
    },
    workflow: 'Provisional credit basis shows "not claimed" for M-03 and M-04.',
    workflowTests: [],
  },
  {
    ...base,
    id: 'SF-13',
    title:
      'Pending baseline approval: submission accepted, implementation pending',
    references: {
      prd: ['§10.4'],
      at: ['AT25'],
      decisions: ['O09'],
    },
    inputs: {
      kind: 'quarter',
      maxPoints: 60,
      milestones: [],
      suppliedFiles: ['ev-minutes'],
      decisions: [],
    },
    calculation: [
      'No officer-approved locked baseline: the denominator does not exist',
      'An empty baseline is a configuration state, not full credit and not zero: provisional and reviewed pending',
    ],
    expected: {
      provisional: { status: 'pending', reason: 'baseline_not_approved' },
      reviewed: [
        {
          revision: 1,
          score: { status: 'pending', reason: 'baseline_not_approved' },
        },
      ],
    },
    workflow:
      'Report received with a receipt; scoring pending until the officer approves or confirms the baseline.',
    workflowTests: [tests.at25],
  },
  {
    ...base,
    id: 'SF-14',
    title: 'Submitted but unreviewed quarter: annual publication blocked',
    references: {
      prd: ['§7.6', '§10.5'],
      at: ['AT14'],
      decisions: ['O03', 'O10'],
    },
    inputs: {
      kind: 'annual',
      cutoff,
      foundations: fullFoundations,
      quarters: [
        fin(4),
        fin(4),
        { status: 'awaiting_review', locked: 4 },
        fin(4),
      ],
    },
    calculation: [
      'Q3 was submitted but has no officer disposition: officer backlog, not institutional nonresponse',
      'It is never treated as I3 = 0 (which would give 85.00): the annual result is pending',
    ],
    expected: { status: 'pending' },
    workflow:
      'Annual result pending with "Q3 awaiting officer review"; publication blocked for this institution.',
    workflowTests: [tests.at14api, tests.at14mock],
  },
  {
    ...base,
    id: 'SF-15',
    title: 'Missing quarter: zero only after authorized officer disposition',
    references: {
      prd: ['§7.3', '§10.5'],
      at: ['AT15', 'AT29'],
      decisions: ['O10'],
    },
    inputs: {
      kind: 'annual',
      cutoff,
      foundations: fullFoundations,
      quarters: [
        fin(4),
        fin(4),
        fin(4),
        { status: 'closed_without_submission', locked: 4 },
      ],
    },
    calculation: [
      'Before closure the result is pending (see SF-02).',
      'After the cutoff and response window, the officer closes Q4 with a reason: I4 = 0',
      'Implementation: 60 × (1 + 1 + 1 + 0) ÷ 4 = 45',
      'Annual: 40 + 45 = 85.00',
    ],
    expected: {
      status: 'calculated',
      foundationPoints: '40.00',
      implementationAverage: '3/4',
      implementationPoints: '45.00',
      total: '85.00',
    },
    workflow:
      'Closure recorded with officer, reason and time; refused before the window and the cutoff have passed.',
    workflowTests: [tests.at29, tests.at15],
  },
  {
    ...base,
    id: 'SF-16',
    title:
      'Superseded foundation: annual credit uses the version effective at cutoff',
    references: {
      prd: ['§10.3 foundation validity'],
      at: ['AT28'],
      decisions: ['O03'],
    },
    inputs: {
      kind: 'annual',
      cutoff,
      foundations: {
        procedures: full,
        riskAssessment: {
          versions: [
            {
              id: 'RA-v1',
              status: 'superseded',
              effectiveFrom: '2026-07-01',
              effectiveTo: '2027-01-31',
              acceptedChecks: 4,
            },
            {
              id: 'RA-v2',
              status: 'active',
              effectiveFrom: '2027-02-01',
              effectiveTo: null,
              acceptedChecks: 2,
            },
          ],
        },
        mitigationPlan: full,
      },
      quarters: [fin(4), fin(4), fin(4), fin(4)],
    },
    calculation: [
      'Cutoff 31 Jul 2027: RA-v2 (effective from 1 Feb 2027) is the valid version; RA-v1 ended 31 Jan 2027',
      'Rfinal = 2/4 from RA-v2; RA-v1’s 4/4 stays in history and supports earlier quarters only',
      'Foundations: 10 + 15 × 2/4 + 15 = 32.50; implementation 60',
      'Annual: 32.50 + 60 = 92.50',
    ],
    expected: {
      status: 'calculated',
      foundationPoints: '32.50',
      implementationAverage: '1/1',
      implementationPoints: '60.00',
      total: '92.50',
    },
    workflow:
      'Earlier quarterly evidence and RA-v1 decisions remain accessible; the annual outcome names RA-v2.',
    workflowTests: [tests.at28],
  },
  {
    ...base,
    id: 'SF-17',
    title:
      'Withdrawn foundation: no credit retained from the withdrawn version',
    references: {
      prd: ['§10.3 foundation validity'],
      at: ['AT28'],
      decisions: ['O03'],
    },
    inputs: {
      kind: 'annual',
      cutoff,
      foundations: {
        procedures: full,
        riskAssessment: full,
        mitigationPlan: {
          versions: [
            {
              id: 'MP-v2',
              status: 'withdrawn',
              effectiveFrom: '2026-07-01',
              effectiveTo: '2027-03-15',
              acceptedChecks: 4,
            },
            {
              id: 'MP-v3',
              status: 'active',
              effectiveFrom: '2027-03-16',
              effectiveTo: null,
              acceptedChecks: 3,
            },
          ],
        },
      },
      quarters: [fin(4), fin(4), fin(4), fin(4)],
    },
    calculation: [
      'MP-v2 is withdrawn and cannot supply current credit; MP-v3 is effective at the cutoff',
      'MP-v3 supports three checks: Mfinal = 3/4 (not 4/4 from MP-v2)',
      'Foundations: 10 + 15 + 15 × 3/4 = 36.25; implementation 60',
      'Annual: 36.25 + 60 = 96.25',
    ],
    expected: {
      status: 'calculated',
      foundationPoints: '36.25',
      implementationAverage: '1/1',
      implementationPoints: '60.00',
      total: '96.25',
    },
    workflow:
      'Withdrawal preserves MP-v2’s evidence and decisions; unsupported current check shows its reason.',
    workflowTests: [tests.at28],
  },
  {
    ...base,
    id: 'SF-18',
    title:
      'One file supporting several claims: each claim needs its own substantiation',
    references: {
      prd: ['§10.4', '§16.1 calculation tests'],
      at: ['AT27'],
      decisions: ['O02'],
    },
    inputs: {
      kind: 'quarter',
      maxPoints: 60,
      milestones: [
        ms('M-01', true, ['ev-register']),
        ms('M-02', true, ['ev-minutes']),
        ms('M-03', true, ['ev-minutes']),
        ms('M-04', true, ['ev-minutes']),
      ],
      suppliedFiles: ['ev-register', 'ev-minutes'],
      decisions: decide(1, {
        'M-01': 'accepted',
        'M-02': 'rejected',
        'M-03': 'accepted',
        'M-04': 'accepted',
      }),
    },
    calculation: [
      'Provisional: every claim references a supplied file → 4/4 → 60.00',
      'Reviewed: the minutes substantiate the CPC (M-03) and IAO (M-04) meetings but not the training (M-02)',
      'Reviewed: 3/4 → 45.00 — one file does not carry credit to every claim that cites it',
    ],
    expected: {
      provisional: calc('4/4', '60.00'),
      reviewed: [{ revision: 1, score: calc('3/4', '45.00') }],
    },
    workflow:
      'Each decision records its own passage reference; replacing the shared file marks every dependent decision for re-review.',
    workflowTests: [tests.at09],
  },
  {
    ...base,
    id: 'SF-19',
    title:
      'Late-submitted evidence proving on-time completion: correction preserves earlier decisions',
    references: {
      prd: ['§3.3', '§10.4'],
      at: ['AT09', 'AT27'],
      decisions: ['O02', 'O09'],
    },
    inputs: {
      kind: 'quarter',
      maxPoints: 60,
      milestones: [
        ms('M-01', true, ['ev-progress-report', 'ev-exception-review']),
        ms('M-02', true, ['ev-minutes']),
        ms('M-03', true, ['ev-minutes']),
        ms('M-04', true, ['ev-minutes']),
      ],
      suppliedFiles: [
        'ev-progress-report',
        'ev-exception-review',
        'ev-minutes',
      ],
      decisions: [
        ...decide(1, {
          'M-01': 'rejected',
          'M-02': 'accepted',
          'M-03': 'accepted',
          'M-04': 'accepted',
        }),
        ...allAccepted(codes(4), 2),
      ],
    },
    calculation: [
      'Revision 1: M-01 unsupported and rejected → 3/4 → 45.00',
      'Revision 2 (clarification response): a dated exception review proves M-01 was completed by quarter end',
      'Re-review accepts M-01; M-02–M-04 carried forward by explicit confirmation → 4/4 → 60.00',
      'Revision 1’s decisions and 45.00 remain in history; nothing is overwritten',
    ],
    expected: {
      provisional: calc('4/4', '60.00'),
      reviewed: [
        { revision: 1, score: calc('3/4', '45.00') },
        { revision: 2, score: calc('4/4', '60.00') },
      ],
    },
    workflow:
      'New revision with the earlier receipt and evidence preserved; recalculation before the cutoff.',
    workflowTests: [tests.at09],
  },
  {
    ...base,
    id: 'SF-20',
    title: 'Late completion: no duplicate milestone credit',
    references: {
      prd: ['§10.4'],
      at: [],
      decisions: ['O09'],
    },
    inputs: {
      kind: 'quarter',
      maxPoints: 60,
      milestones: codes(4, 5).map((code) => ms(code, true, ['ev-q2'])),
      outOfBaseline: [ms('M-01', true, ['ev-q2'])],
      suppliedFiles: ['ev-q2'],
      decisions: allAccepted(codes(4, 5)),
    },
    calculation: [
      'Q1’s M-01 was not completed by Q1 end: Q1 keeps I1 = 3/4',
      'Q2 reports M-01 as corrective progress, but M-01 is not in the Q2 baseline (M-05–M-08)',
      'Q2: 4/4 → 60.00, not 5/4 and not a second credit for M-01',
    ],
    expected: {
      provisional: calc('4/4', '60.00'),
      reviewed: [{ revision: 1, score: calc('4/4', '60.00') }],
    },
    workflow: 'M-01 corrective progress visible in Q2 without score credit.',
    workflowTests: [],
  },
  {
    ...base,
    id: 'SF-21',
    title: 'Plan size: four-milestone baseline, three accepted',
    references: {
      prd: ['§10.4', '§10.7'],
      at: [],
      decisions: ['O09'],
    },
    inputs: {
      kind: 'quarter',
      maxPoints: 60,
      milestones: codes(4).map((code) => ms(code, true, ['ev-1'])),
      suppliedFiles: ['ev-1'],
      decisions: decide(1, {
        'M-01': 'accepted',
        'M-02': 'accepted',
        'M-03': 'accepted',
        'M-04': 'rejected',
      }),
    },
    calculation: ['Reviewed: 3/4 = 0.75 → 60 × 0.75 = 45.00'],
    expected: {
      provisional: calc('4/4', '60.00'),
      reviewed: [{ revision: 1, score: calc('3/4', '45.00') }],
    },
    workflow: 'Plan size 4 shown beside the score in comparisons.',
    workflowTests: [],
  },
  {
    ...base,
    id: 'SF-22',
    title: 'Plan size: twelve-milestone baseline, nine accepted',
    references: {
      prd: ['§10.4', '§10.7'],
      at: [],
      decisions: ['O09'],
    },
    inputs: {
      kind: 'quarter',
      maxPoints: 60,
      milestones: codes(12).map((code) => ms(code, true, ['ev-1'])),
      suppliedFiles: ['ev-1'],
      decisions: decide(1, {
        ...Object.fromEntries(codes(9).map((code) => [code, 'accepted'])),
        ...Object.fromEntries(codes(3, 10).map((code) => [code, 'rejected'])),
      }),
    },
    calculation: [
      'Reviewed: 9/12 = 0.75 → 60 × 0.75 = 45.00, the same as SF-21',
      'Equal scores represent different accepted plans, not equal prevention impact',
    ],
    expected: {
      provisional: calc('12/12', '60.00'),
      reviewed: [{ revision: 1, score: calc('9/12', '45.00') }],
    },
    workflow: 'Plan size 12 shown beside the score; no league-table claim.',
    workflowTests: [],
  },
  {
    ...base,
    id: 'SF-23',
    title:
      'Denominator inflation, approved baseline: committee obligations only',
    references: {
      prd: ['§10.7 fairness and gaming example'],
      at: ['AT31'],
      decisions: ['O09'],
    },
    inputs: {
      kind: 'quarter',
      maxPoints: 60,
      milestones: [
        ms('CPC', true, ['ev-cpc-minutes']),
        ms('IAO', true, ['ev-iao-minutes']),
        ms('A-01', false),
        ms('A-02', false),
      ],
      suppliedFiles: ['ev-cpc-minutes', 'ev-iao-minutes'],
      decisions: decide(1, {
        CPC: 'accepted',
        IAO: 'accepted',
        'A-01': 'rejected',
        'A-02': 'rejected',
      }),
    },
    calculation: [
      'Two committee obligations + two substantive activities; only the committees completed',
      'Reviewed: 2/4 = 0.50 → 60 × 0.50 = 30.00',
    ],
    expected: {
      provisional: calc('2/4', '30.00'),
      reviewed: [{ revision: 1, score: calc('2/4', '30.00') }],
    },
    workflow: 'The approved four-milestone baseline stays the denominator.',
    workflowTests: [tests.at31],
  },
  {
    ...base,
    id: 'SF-24',
    title:
      'Denominator inflation, rejected proposal: eight trivial tasks added',
    references: {
      prd: ['§10.7 fairness and gaming example'],
      at: ['AT31'],
      decisions: ['O09'],
    },
    inputs: {
      kind: 'quarter',
      maxPoints: 60,
      milestones: [
        ms('CPC', true, ['ev-1']),
        ms('IAO', true, ['ev-1']),
        ms('A-01', false),
        ms('A-02', false),
        ...codes(8, 1).map((code) => ms(`T${code}`, true, ['ev-1'])),
      ],
      suppliedFiles: ['ev-1'],
      decisions: [],
    },
    calculation: [
      'If activated, the inflated plan would show 10/12 = 83.33% (60 × 10/12 = 50.00) for the same nonachievement',
      'Committee obligations would shrink from half to one sixth of the denominator',
      'This is why the proposal must not activate: the arithmetic is shown only to expose the gaming',
    ],
    expected: {
      provisional: calc('10/12', '50.00'),
      reviewed: [{ revision: 1, score: awaiting }],
    },
    workflow:
      'Proposal returned by the officer for artificial fragmentation; it never becomes a locked baseline, so 50.00 is never scored.',
    workflowTests: [tests.at31],
  },
  {
    ...base,
    id: 'SF-25',
    title: 'Future-only amendment: earlier denominators unchanged',
    references: {
      prd: ['§10.4', '§17.1 DEMO-006'],
      at: ['AT17'],
      decisions: ['O09'],
    },
    inputs: {
      kind: 'annual',
      cutoff,
      foundations: fullFoundations,
      quarters: [fin(4), fin(3), fin(4, 5), fin(5, 5)],
    },
    calculation: [
      'Amendment confirmed during Q2 adds one milestone, effective from the unopened Q3',
      'Q1 4/4 = 1 and Q2 3/4 = 0.75 keep their original baselines; Q3 4/5 = 0.80; Q4 5/5 = 1',
      'Implementation average: (1 + 0.75 + 0.80 + 1) ÷ 4 = 3.55 ÷ 4 = 0.8875 (71/80)',
      'Implementation: 60 × 0.8875 = 53.25; annual: 40 + 53.25 = 93.25',
    ],
    expected: {
      status: 'calculated',
      foundationPoints: '40.00',
      implementationAverage: '71/80',
      implementationPoints: '53.25',
      total: '93.25',
    },
    workflow:
      'Amendment carries a reason and officer confirmation; an amendment for an opened period is refused; the original baseline is retained.',
    workflowTests: [tests.at17],
  },
  {
    ...base,
    id: 'SF-26',
    title: 'Rounding boundary: exact value 45.625 displays 45.63 (half-up)',
    references: {
      prd: ['§10.5'],
      at: [],
      decisions: ['O03'],
    },
    inputs: {
      kind: 'annual',
      cutoff,
      foundations: fullFoundations,
      quarters: [fin(3, 8), fin(0), fin(0), fin(0)],
    },
    calculation: [
      'Implementation average: (3/8 + 0 + 0 + 0) ÷ 4 = 3/32',
      'Implementation: 60 × 3/32 = 5.625 exactly → displayed 5.63',
      'Annual: 40 + 5.625 = 45.625 exactly → displayed 45.63 (half-even would give 45.62)',
    ],
    expected: {
      status: 'calculated',
      foundationPoints: '40.00',
      implementationAverage: '3/32',
      implementationPoints: '5.63',
      total: '45.63',
    },
    workflow:
      'Finalized; displayed values round half-up from the exact fraction.',
    workflowTests: [],
  },
  {
    ...base,
    id: 'SF-27',
    title: 'Totals from unrounded components, not summed rounded parts',
    references: {
      prd: ['§10.5'],
      at: [],
      decisions: ['O03'],
    },
    inputs: {
      kind: 'annual',
      cutoff,
      foundations: fullFoundations,
      quarters: [fin(1, 7), fin(1, 7), fin(1, 7), fin(0, 7)],
    },
    calculation: [
      'Each of Q1–Q3 contributes 60 × 1/7 ÷ 4 = 15/7 = 2.142857… (displayed 2.14)',
      'Summing the displayed contributions gives 2.14 × 3 = 6.42 → 46.42 (wrong)',
      'Exact: 60 × (3/7) ÷ 4 = 45/7 = 6.428571… → 6.43; annual 40 + 45/7 = 46.428571… → 46.43',
    ],
    expected: {
      status: 'calculated',
      foundationPoints: '40.00',
      implementationAverage: '3/28',
      implementationPoints: '6.43',
      total: '46.43',
    },
    workflow:
      'Finalized; stored fractions are exact, only displayed values are rounded.',
    workflowTests: [],
  },
];

export interface ReviewRecord {
  role: string;
  reviewer: string;
  status: 'pending' | 'approved' | 'changes_requested';
  /** ISO date of the review, once given. */
  date: string | null;
  notes: string;
}

/**
 * Human review of this worksheet (HP2-11 handoff). Executable tests passing is not approval:
 * record each review here, with its date, when it happens.
 */
export const reviews: ReviewRecord[] = [
  {
    role: 'Fixture structure and technical correctness',
    reviewer: 'Patrick',
    status: 'pending',
    date: null,
    notes: '',
  },
  {
    role: 'Approval of the independently derived expected results',
    reviewer: 'Henry',
    status: 'pending',
    date: null,
    notes: '',
  },
];

export interface DefectRecord {
  fixtureId: string;
  /** Linear issue, e.g. HP2-xx. */
  issue: string;
  summary: string;
  retest: string | null;
}

/** Failures linked to defects, with retest outcomes. */
export const defects: DefectRecord[] = [];

/** Points the reviewers should settle; not failures of an executed fixture. */
export const openQuestions: string[] = [
  'The API and the mock score the foundation version whose status is `active`, while PRD §10.3 asks for the version effective at the original cutoff. They agree for SF-16 and SF-17, but would differ if a replacement recorded before evaluation took effect only after the cutoff. Confirm whether that case can arise, and add a fixture if it can.',
  'With a foundation withdrawn and no valid replacement, PRD §10.3 says the final fraction reflects the deficiency (0/4); the implementation shows the foundation as not reviewed, so the annual result stays pending. Confirm the intended disposition path.',
  'Workflow states (publication blocked, closure refused before the cutoff, amendment and inflated-proposal refusal) are executed by the integration and mock tests each fixture lists, not by the worksheet runner. Retest those when the fixture or the rule changes.',
];
