import {
  defects,
  inputVersions,
  openQuestions,
  reviews,
  scoringFixtures,
  worksheetVersion,
  type AnnualExpected,
  type ExpectedScore,
  type QuarterExpected,
} from './catalogue.js';
import { profileConformance, runFixture } from './conformance.js';

/** Renders the HP2-11 worksheet: fixtures, independent calculation, expected and actual. */

const scoreText = (score: ExpectedScore) =>
  score.status === 'calculated'
    ? `${score.points} (${score.fraction})`
    : `pending: ${score.reason.replaceAll('_', ' ')}`;

function resultText(result: QuarterExpected | AnnualExpected) {
  if ('provisional' in result) {
    const reviewed = result.reviewed.map((row) =>
      result.reviewed.length > 1
        ? `reviewed r${row.revision} ${scoreText(row.score)}`
        : `reviewed ${scoreText(row.score)}`,
    );
    const late =
      result.daysLate === undefined
        ? []
        : [
            `${result.daysLate} day${result.daysLate === 1 ? '' : 's'} late, no deduction`,
          ];
    return [
      `provisional ${scoreText(result.provisional)}`,
      ...reviewed,
      ...late,
    ].join('<br>');
  }
  return result.status === 'pending'
    ? 'pending (no annual result)'
    : `**${result.total}** = ${result.foundationPoints} + ${result.implementationPoints} (average ${result.implementationAverage})`;
}

const cell = (text: string) => text.replaceAll('|', '\\|');

export function renderWorksheet() {
  const rows = scoringFixtures.map(runFixture);
  const passed = rows.filter((row) => row.outcome === 'pass').length;
  const reviewStatus = reviews.every((review) => review.status === 'approved')
    ? 'Approved'
    : `Pending (${reviews
        .filter((review) => review.status !== 'approved')
        .map((review) => review.reviewer)
        .join(', ')})`;
  const profile = profileConformance();
  const lines = [
    '# HP2-11 scoring worksheet',
    '',
    '<!-- Generated by `pnpm worksheet` from packages/contracts/src/scoring-fixtures. Do not edit by hand. -->',
    '',
    `Independent scoring reference for PRD §10, worksheet version ${worksheetVersion}. ${inputVersions.label}`,
    '',
    `Engine run: **${passed} of ${rows.length} fixtures pass**. Human review: **${reviewStatus}**. Passing executable checks is not approval of the expected results.`,
    '',
    '## Inputs and method',
    '',
    `- Profile: ${inputVersions.profile.name} (\`${inputVersions.profile.id}\` v${inputVersions.profile.version}), formula \`${inputVersions.formula}\`, rounding \`${inputVersions.rounding}\`; form \`${inputVersions.form.id}\` v${inputVersions.form.version}. The implementation's default profile is \`${profile.id}\` v${profile.version}, \`${profile.formula}\`, \`${profile.rounding}\`.`,
    `- Weights: procedures ${inputVersions.weights.procedures}, risk assessment ${inputVersions.weights.riskAssessment}, mitigation plan ${inputVersions.weights.mitigationPlan}, implementation ${inputVersions.weights.implementation}.`,
    '- Foundation fraction = accepted checks ÷ 4 (binary checks, PRD §10.3). Quarter fraction Iq = accepted milestone weight ÷ all locked milestone weight (PRD §10.4); demo milestone weights are 1.',
    '- Annual = 10P + 15R + 15M + 60 × (I1 + I2 + I3 + I4) ÷ 4, foundations once, all four quarters kept (PRD §10.5). Exact fractions throughout; only displayed values are rounded, half-up to two decimals.',
    '- Expected values are written by hand from the PRD in `catalogue.ts`. `worksheet.ts` recomputes them without the scoring engine, API, mock or seed; `conformance.ts` executes each fixture against the shared engine (`scoreSummary`, `annualTotal`, `daysLate`) that the API and the mock call.',
    '- Decision register: [O01–O03, O09, O10](../domain-decisions.md). An approved change to those rules updates the affected expected values explicitly: bump the fixture version and record the change.',
    '',
    '## Evidence',
    '',
    '| Fixture ID | Input versions | PRD/AT reference | Independent calculation | Expected | Actual | Outcome | Review |',
    '| --- | --- | --- | --- | --- | --- | --- | --- |',
    ...rows.map(({ fixture, actual, outcome }) =>
      [
        `**${fixture.id}** ${fixture.title}`,
        `fixture v${fixture.version}; ${inputVersions.profile.id} v${inputVersions.profile.version}; ${inputVersions.form.id}`,
        [
          ...fixture.references.prd,
          ...fixture.references.at,
          ...fixture.references.decisions,
        ].join(', '),
        fixture.calculation.join('<br>'),
        resultText(fixture.expected),
        resultText(actual),
        outcome === 'pass' ? 'Pass' : '**Fail**',
        reviewStatus,
      ]
        .map(cell)
        .join(' | ')
        .replace(/^/, '| ')
        .replace(/$/, ' |'),
    ),
    '',
    '## Expected workflow state',
    '',
    '| Fixture ID | Workflow state | Executed by |',
    '| --- | --- | --- |',
    ...scoringFixtures.map(
      (fixture) =>
        `| ${fixture.id} | ${cell(fixture.workflow)} | ${
          fixture.workflowTests.length
            ? fixture.workflowTests
                .map((test) => cell(`\`${test}\``))
                .join('<br>')
            : 'Engine run only'
        } |`,
    ),
    '',
    '## Defects and retests',
    '',
    ...(defects.length
      ? [
          '| Fixture ID | Issue | Discrepancy | Retest |',
          '| --- | --- | --- | --- |',
          ...defects.map(
            (defect) =>
              `| ${defect.fixtureId} | ${defect.issue} | ${cell(defect.summary)} | ${defect.retest ?? 'Not yet retested'} |`,
          ),
        ]
      : [
          'None recorded. A failing fixture is linked to a Linear defect here before it is retested.',
        ]),
    '',
    '## Open questions for review',
    '',
    ...openQuestions.map((question, index) => `${index + 1}. ${question}`),
    '',
    '## Review and sign-off',
    '',
    '| Review | Reviewer | Status | Date | Notes |',
    '| --- | --- | --- | --- | --- |',
    ...reviews.map(
      (review) =>
        `| ${review.role} | ${review.reviewer} | ${review.status.replaceAll('_', ' ')} | ${review.date ?? '—'} | ${cell(review.notes) || '—'} |`,
    ),
    '',
    'Record each review in `reviews` in `packages/contracts/src/scoring-fixtures/catalogue.ts` and regenerate this file, so the evidence stays beside the worksheet.',
    '',
  ];
  return lines.join('\n');
}
