import {
  defects,
  inputVersions,
  inputReviews,
  openQuestions,
  reviewedFixtures,
  scoringFixtures,
  scriptedYear,
  scriptedYearCases,
  worksheetVersion,
  type AnnualExpected,
  type ExpectedScore,
  type QuarterExpected,
} from './catalogue.js';
import { profileConformance, runFixture } from './conformance.js';

/** Renders the HP2-11 worksheet: fixtures, independent calculation, expected and actual. */

const scoreText = (score: ExpectedScore) =>
  score.status === 'calculated'
    ? `${score.points} (${score.fraction})`
    : `pending: ${score.reason.replaceAll('_', ' ')}`;

function resultText(result: QuarterExpected | AnnualExpected) {
  if ('provisional' in result) {
    const reviewed = result.reviewed.map((row) =>
      result.reviewed.length > 1
        ? `reviewed r${row.revision} ${scoreText(row.score)}`
        : `reviewed ${scoreText(row.score)}`,
    );
    const late =
      result.daysLate === undefined
        ? []
        : [
            `${result.daysLate} day${result.daysLate === 1 ? '' : 's'} late, no deduction`,
          ];
    return [
      `provisional ${scoreText(result.provisional)}`,
      ...reviewed,
      ...late,
    ].join('<br>');
  }
  return result.status === 'pending'
    ? 'pending (no annual result)'
    : `**${result.total}** = ${result.foundationPoints} + ${result.implementationPoints} (average ${result.implementationAverage})`;
}

const cell = (text: string) => text.replaceAll('|', '\\|');

export function renderWorksheet() {
  const rows = scoringFixtures.map(runFixture);
  const passed = rows.filter((row) => row.outcome === 'pass').length;
  const agreed = reviewedFixtures();
  const reviewCell = (id: string) => {
    const review = [...inputReviews]
      .reverse()
      .find((candidate) => candidate.fixtures.includes(id));
    if (!review) return 'Not yet reviewed';
    return `${agreed.has(id) ? 'Inputs agreed' : 'Changes requested'} (${review.reviewers.join(', ')}, ${review.date})`;
  };
  const reviewSummary =
    agreed.size === 0
      ? 'not yet recorded'
      : `${agreed.size} of ${rows.length} fixtures agreed`;
  const profile = profileConformance();
  const lines = [
    '# HP2-11 scoring worksheet',
    '',
    '<!-- Generated by `pnpm worksheet` from packages/contracts/src/scoring-fixtures. Do not edit by hand. -->',
    '',
    `Independent scoring reference for PRD §10, worksheet version ${worksheetVersion}. ${inputVersions.label}`,
    '',
    `Engine run: **${passed} of ${rows.length} fixtures pass**. Team review of inputs: **${reviewSummary}**. Executable checks do not replace the team review of the inputs that HP2-11 asks for.`,
    '',
    '## Inputs and method',
    '',
    `- Profile: ${inputVersions.profile.name} (\`${inputVersions.profile.id}\` v${inputVersions.profile.version}), formula \`${inputVersions.formula}\`, rounding \`${inputVersions.rounding}\`; form \`${inputVersions.form.id}\` v${inputVersions.form.version}. The implementation's default profile is \`${profile.id}\` v${profile.version}, \`${profile.formula}\`, \`${profile.rounding}\`.`,
    `- Weights: procedures ${inputVersions.weights.procedures}, risk assessment ${inputVersions.weights.riskAssessment}, mitigation plan ${inputVersions.weights.mitigationPlan}, implementation ${inputVersions.weights.implementation}.`,
    '- Foundation fraction = accepted checks ÷ 4 (binary checks, PRD §10.3). Quarter fraction Iq = accepted milestone weight ÷ all locked milestone weight (PRD §10.4); demo milestone weights are 1.',
    '- Annual = 10P + 15R + 15M + 60 × (I1 + I2 + I3 + I4) ÷ 4, foundations once, all four quarters kept (PRD §10.5). Exact fractions throughout; only displayed values are rounded, half-up to two decimals.',
    '- Expected values are written by hand from the PRD in `catalogue.ts`. `worksheet.ts` recomputes them without the scoring engine, API, mock or seed; `conformance.ts` executes each fixture against the shared engine (`scoreSummary`, `annualTotal`, `daysLate`) that the API and the mock call.',
    '- Decision register: [O01–O03, O09, O10](../domain-decisions.md). An approved change to those rules updates the affected expected values explicitly: bump the fixture version and record the change.',
    '',
    '## Evidence',
    '',
    '| Fixture ID | Input versions | PRD/AT reference | Independent calculation | Expected | Actual | Outcome | Review |',
    '| --- | --- | --- | --- | --- | --- | --- | --- |',
    ...rows.map(({ fixture, actual, outcome }) =>
      [
        `**${fixture.id}** ${fixture.title}`,
        `fixture v${fixture.version}; ${inputVersions.profile.id} v${inputVersions.profile.version}; ${inputVersions.form.id}`,
        [
          ...fixture.references.prd,
          ...fixture.references.at,
          ...fixture.references.decisions,
        ].join(', '),
        fixture.calculation.join('<br>'),
        resultText(fixture.expected),
        resultText(actual),
        outcome === 'pass' ? 'Pass' : '**Fail**',
        reviewCell(fixture.id),
      ]
        .map(cell)
        .join(' | ')
        .replace(/^/, '| ')
        .replace(/$/, ' |'),
    ),
    '',
    '## Expected workflow state',
    '',
    '| Fixture ID | Workflow state | Executed by |',
    '| --- | --- | --- |',
    ...scoringFixtures.map(
      (fixture) =>
        `| ${fixture.id} | ${cell(fixture.workflow)} | ${
          fixture.workflowTests.length
            ? fixture.workflowTests
                .map((test) => cell(`\`${test}\``))
                .join('<br>')
            : 'Engine run only'
        } |`,
    ),
    '',
    '## Scripted demonstration year',
    '',
    "The eight fictional institutions of PRD §17.1 and the fixture holding each one’s annual inputs. HP2-36 reconciles the persisted API against these cases: `import { scriptedYearCases } from '@cpi/contracts/scoring-fixtures'`.",
    '',
    '| Institution | Scenario | Fixture | Foundation checks (P/R/M) | Quarter milestones (Q1–Q4) | Foundation | Implementation | Total |',
    '| --- | --- | --- | --- | --- | --- | --- | --- |',
    ...scriptedYearCases().map((row) => {
      const quarters = row.quarterAcceptedMilestones.map((accepted, index) =>
        row.closedQuarters.includes(index + 1)
          ? 'closed 0'
          : `${accepted}/${row.quarterLockedMilestones[index]}`,
      );
      return `| ${row.institutionId} | ${cell(scriptedYear.find((item) => item.institutionId === row.institutionId)!.scenario)} | ${row.fixtureId} | ${row.foundationAcceptedChecks.map((checks) => `${checks}/4`).join(', ')} | ${quarters.join(', ')} | ${row.expectedFoundationPoints} | ${row.expectedImplementationPoints} | ${row.expectedTotal} |`;
    }),
    '',
    '## Defects and retests',
    '',
    ...(defects.length
      ? [
          '| Fixture ID | Issue | Discrepancy | Retest |',
          '| --- | --- | --- | --- |',
          ...defects.map(
            (defect) =>
              `| ${defect.fixtureId} | ${defect.issue} | ${cell(defect.summary)} | ${defect.retest ?? 'Not yet retested'} |`,
          ),
        ]
      : [
          'None recorded. A failing fixture is linked to a Linear defect here before it is retested.',
        ]),
    '',
    '## Open questions for review',
    '',
    ...openQuestions.map((question, index) => `${index + 1}. ${question}`),
    '',
    '## Team review of inputs',
    '',
    'HP2-11 asks for a team review of the fixture inputs and hand calculations; no external sign-off or formal approval is required.',
    '',
    ...(inputReviews.length
      ? [
          '| Date | Reviewers | Fixtures | Outcome | Notes |',
          '| --- | --- | --- | --- | --- |',
          ...inputReviews.map(
            (review) =>
              `| ${review.date} | ${review.reviewers.join(', ')} | ${review.fixtures.join(', ')} | ${review.outcome === 'inputs_agreed' ? 'Inputs agreed' : 'Changes requested'} | ${cell(review.notes) || '—'} |`,
          ),
        ]
      : ['No review recorded yet.']),
    '',
    'Record each review in `inputReviews` in `packages/contracts/src/scoring-fixtures/catalogue.ts` and run `pnpm worksheet`, so the evidence stays beside the worksheet.',
    '',
  ];
  return lines.join('\n');
}
